apiVersion: v1
kind: Service
metadata:
  name: mywebsvc
  labels:
    app: alpinesample
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: websvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebsvc
  labels:
    app: alpinesample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpinesample
  template:
    metadata:
      labels:
        app: alpinesample
    spec:
      containers:
      - name: alpinesample
        image: bhoobal/alpineaspnetcore:1.0
        ports:
        - containerPort: 80
