apiVersion: v1
kind: Pod
metadata:
  name: webapplication-deployment
spec:
  containers:
    - name: corewebapp
      image: bhoobal/alpineaspnetcore:1.0
      envFrom:
      - configMapRef:
          name: exconfigmap
  restartPolicy: Never